[package]
name = "server"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = "1.0.126"
actix-cors = "0.5.4"
actix-web = "3.3.2"
juniper = "0.15.6"
serde_json = "1.0.64"
serde_derive = "1.0.126"
env_logger = "0.8.4"
diesel = { version = "1.4.7", features = ["postgres"] }
dotenv = "0.15.0"
